apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: processor-keda
  namespace: trading-system
spec:
  scaleTargetRef:
    name: transaction-processor
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.default.svc.cluster.local:9092
      consumerGroup: transaction-processor
      topic: transactions
      lagThreshold: "50"