apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing-service
  template:
    metadata:
      labels:
        app: pricing-service
    spec:
      containers:
        - name: pricing
          image: phipho/pricing-service:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP
              value: kafka.{{ .Release.Namespace }}.svc.cluster.local:9092