apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-consumer
  namespace: trading-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-consumer
  template:
    metadata:
      labels:
        app: db-consumer
    spec:
      containers:
      - name: consumer
        image: transaction-consumer:dev
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP
          value: kafka.trading-system.svc.cluster.local:9092
        - name: POSTGRES_HOST
          value: postgres-postgresql.trading-system.svc.cluster.local
        envFrom:
        - secretRef:
            name: postgres-secret