apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-processor
  namespace: trading-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-processor
  template:
    metadata:
      labels:
        app: transaction-processor
    spec:
      containers:
      - name: processor
        image: transaction-processor:dev
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP
          value: kafka.trading-system.svc.cluster.local:9092
        - name: TRANSACTIONS_TOPIC
          value: transactions
        - name: PRICES_TOPIC
          value: prices
        - name: OUTPUT_TOPIC
          value: transactions_processed